---
- name: clone the DatabaseAPI repo
  ansible.builtin.git:
    repo: 'https://{{ git_token }}@github.com/rvalavi/DatabaseAPI.git' # update repo ower after transfer to cesaraustralia
    dest: /home/{{ remote_user }}/DatabaseAPI
    update: yes

- name: update app.py files with database password for the api
  replace:
    path: /home/{{ remote_user }}/DatabaseAPI/app.py
    regexp: "dbpassword"
    replace: "{{ dbpass }}"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"

- name: clone the CesarDatabase repo
  ansible.builtin.git:
    repo: 'https://{{ git_token }}@github.com/cesaraustralia/CesarDatabase.git'
    dest: /srv/shiny-server/CesarDatabase
    update: yes

- name: clone the ausresistancemap repo
  ansible.builtin.git:
    repo: 'https://{{ git_token }}@github.com/cesaraustralia/ausresistancemap.git'
    dest: /srv/shiny-server/AusResistanceMap
    update: yes

- name: clone the pestimator repo
  ansible.builtin.git:
    repo: 'https://github.com/cesaraustralia/daragrub.git'
    dest: /srv/shiny-server/Pestimator
    update: yes

- name: clone the pestimator repo into predict-a-pest
  ansible.builtin.git:
    repo: 'https://github.com/cesaraustralia/daragrub.git'
    dest: /srv/shiny-server/predict-a-pest
    update: yes

- name: clone the LeafMinerShinyObs repo
  ansible.builtin.git:
    repo: 'https://{{ git_token }}@github.com/cesaraustralia/LeafMinerShinyObs.git'
    dest: /srv/shiny-server/LeafMinerShinyObs
    update: yes

- name: clone the SugarPestsSDM repo
  ansible.builtin.git:
    repo: 'https://github.com/cesaraustralia/SugarPestsSDM.git'
    dest: /srv/shiny-server/SugarPestsSDM
    update: yes

- name: change shiny server file permissions (github action req)
  become: yes
  file:
    path: /srv
    state: directory
    recurse: yes
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
