---
- hosts: all

  tasks:
    - name: Install R
      become: yes
      include: tasks/install-r.yml
    - name: Install R packages
      become: yes
      include: tasks/install-packages.yml
    # - name: Install RStudio server
      # include: tasks/install-rstudio-server.yml
    # - name: Clone R scripts
     #  ansible.builtin.git:
      #  repo: https://github.com/cesaraustralia/GeneticRiskIndex
      #  dest: ~/GeneticRiskIndex
