---
- name: add aws ecr access key to the server
  become: yes
  ansible.builtin.shell: |
    aws ecr get-login-password --region {{ region }} | docker login --username AWS --password-stdin {{ ecr_repo_url }}

- name: create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
  loop:
    - /home/{{ remote_user }}/docker
    - /home/{{ remote_user }}/db_upload
    - /home/{{ remote_user }}/db_backup

- name: copy docker-compose file to the server (including variables)
  ansible.builtin.template:
    src: "../docker/docker-compose.yml"
    dest: /home/{{ remote_user }}/docker
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"

- name: deploy docker compose stack
  docker_compose:
    project_src: /home/{{ remote_user }}/docker
    files:
      - docker-compose.yml
