# add docker network here to connect to db form shiny wiht localhost and no lag
version: "3.3"
services:
  postgis:
    image: postgis/postgis:latest
    ports:
      - 5432:5432
    environment:
     - POSTGRES_USER=dbuser
     - POSTGRES_PASSWORD=dbpass
     - POSTGRES_DB=dbname
    volumes:
     - /var/lib/postgresql/data:/var/lib/postgresql/data
     - /home/ubuntu/db_upload:/home/db_upload
  shiny:
    image: shinyimage
    ports:
     - 80:3838
    volumes:
     - /srv/shiny-server:/srv/shiny-server
     - /var/log/shiny-server:/var/log/shiny-server
     - /home/ubuntu/db_upload:/home/db_upload
  rstudio:
    image: rocker/rstudio:latest
    ports:
      - 8787:8787
    environment:
      - PASSWORD=rstudiopass
    volumes:
      - /srv/shiny-server:/srv/shiny-server
      - /var/log/shiny-server:/var/log/shiny-server
