version: "3.3"
services:
  mypostgis:
    image: postgis/postgis
    ports:
      - 5432:5432
    environment:
     - POSTGRES_PASSWORD=cesarau
     - POSTGRES_USER=admin
     - POSTGRES_DB=postgres
    volumes:
     - /var/lib/postgresql/data:/var/lib/postgresql/data
  myshiny:
    image: "${shiny_image}"
    ports:
     - 3838:3838
    volumes:
     - /srv/shiny-server:/srv/shiny-server
     - /var/log/shiny-server:/var/log/shiny-server
