version: "3.3"
services:
  postgis:
    image: postgis/postgis:latest # other versions don't work!
    container_name: postgis
    ports:
      - 5432:5432
    environment:
     - POSTGRES_USER={{ dbuser }}
     - POSTGRES_PASSWORD={{ dbpass }}
     - POSTGRES_DB={{ dbname }}
    volumes:
     - /var/lib/postgresql/data:/var/lib/postgresql/data
     - /home/{{ remote_user }}/.db_upload:/home/db_upload # connection to database shiny app
  shiny:
    user: "${UID}:${GID}"
    image: "{{ ecr_repo_url }}:{{ shiny_tag }}"
    container_name: shiny
    ports:
     - 3838:3838
    volumes:
     - /srv/shiny-server:/srv/shiny-server
     - /var/log/shiny-server:/var/log/shiny-server
     - /home/{{ remote_user }}/.db_upload:/home/shiny/.db_upload # connection to database shiny app
  rstudio:
    image: rocker/tidyverse:4.1.2
    container_name: rstudio
    ports:
      - 8787:8787
    environment:
      - USER={{ rsuser }}
      - PASSWORD={{ rspass }}
    volumes:
      - /srv/shiny-server:/srv/shiny-server
      - /var/log/shiny-server:/var/log/shiny-server
