---

- name: Add the APT key
  apt_key: keyserver=keyserver.ubuntu.com id=51716619E084DAB9

- name: Add APT repository
  apt_repository: repo="deb https://cran.rstudio.com/bin/linux/ubuntu/ {{ ansible_distribution_release }}-cran40/" mode=644

- name: Install R
  apt: name=r-base update_cache=yes
