---
- name: update the server
  apt:
    upgrade: dist
    # update_cache: yes ## not supported anymore
    cache_valid_time: 3600


- name: install required packges on the server
  apt:
    state: present
    # update_cache: yes
    name:
      - git
      - awscli
      - unattended-upgrades


- name: installa docker dependencies
  apt:
    state: present
    # update_cache: yes
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common
      - lsb-release
- name: add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: add docker to apt repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
- name: install docker apps
  apt:
    state: latest
    # update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose

- name: make sure that docker was started and enabled
  service:
    name: docker
    state: started
    enabled: yes

- name: install caddy requirements
  apt:
    state: present
    # update_cache: yes
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https

- name: install caddy for tsl/ssl certificate (activating HTTPS)
  become: yes
  ansible.builtin.shell: |
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
    apt update
    apt -y install caddy
    