# yaml file for setting up the server apps and tasks
---
- name: Configure the server
  hosts: all
  remote_user: "{{ remote_user }}"
  become: yes
  vars_files:
    - ansible_vars_file.yml

  # define the roles/takse for ansible to run
  roles: 
    - install_packages
    - setup_shinyapps
    - setup_containers
    - setup_database
    # - setup_backups

