---
- name: create a cron job for db backup
  ansible.builtin.cron:
    name: backup the database
    weekday: "0"
    minute: "0"
    hour: "3"
    user: root
    job: 'docker exec -t docker_postgis_1 pg_dumpall -c -U {{ dbuser }} | gzip > /home/{{ remote_user }}/db_backup/pg_backup_`date +"\%y-\%m-\%d_\%H_\%M_\%S"`.gz'

- name: create a cron job for db backup
  ansible.builtin.cron:
    name: the latest db backup
    weekday: "0"
    minute: "5"
    hour: "3"
    user: root
    job: 'docker exec -t docker_postgis_1 pg_dumpall -c -U {{ dbuser }} | gzip > /home/{{ remote_user }}/db_backup/pg_backup_latest.gz'

- name: create a cron job sending backup to s3
  ansible.builtin.cron:
    name: sync backup with s3
    weekday: "0"
    minute: "15"
    hour: "3"
    user: root
    job: 'aws s3 sync /home/{{ remote_user }}/db_backup/ s3://{{ s3_bucket }}/database-backups/ && sudo rm /home/{{ remote_user }}/db_backup/*'

