name: Render HTML document of RMarkdown

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  render_document:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Render document
        uses: lc5415/rmarkdown-action@master
        with:
          input_file: docs/index.Rmd
          output_format: html_document
